controller:
  hero_chassis_controller:
    type: hero_chassis_controller/HeroChassisController
    wheel_radius: 0.1
    chassis_width: 0.5
    chassis_length: 0.5

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50